### PR TITLE
fixes #4

### LINKED ISSUE #4: Improving model accuracy through enhanced null value handling
Explore alternate methods for handling null values in the dataset. This issue encompasses the research and implementation of these methods to achieve higher predictive performance. Make a pull request if you're able to increase the model's accuracy just by enhancing how the null values are handled.

### PR DESCRIPTION
**Pull request by UmeshKumaar15**
fix: Improved model accuracy by enhanced null value handling.

### CODE REVIEW

**Comment by rsashank** [comment]
Great work @UmeshKumaar15.

However, there's a conflict stemming from the recently merged PR that resolved the `test_train_split` issue. To proceed, could you please make the necessary adjustments in accordance with the current version of `loan_approval.ipynb`. Additionally, please ensure to re-execute the code cells, it appears that in your current commit code cells haven't been executed anew.

**Comment by UmeshKumaar15** [comment]
@rsashank Hi, So now I have to clone the updated repo and fix my issue to cope with the previously merged other participant's code?

**Comment by rsashank** [comment]
> @rsashank Hi, So now I have to clone the updated repo and fix my issue to cope with the previously merged other participant's code?

The current implementation hasn't made a change to the accuracy, but the current code looks cleaner. Hence,  I'll manage conflicts and merge. You will be given points for the same.

**Comment by UmeshKumaar15** [comment]
> > @rsashank Hi, So now I have to clone the updated repo and fix my issue to cope with the previously merged other participant's code?
> 
> The current implementation hasn't made a change to the accuracy, but the current code looks cleaner. Hence, I'll manage conflicts and merge. You will be given points for the same.

Great to hear and thanks for the help!

**Pull request closed without merging**
