### PR TITLE
fixes #3

### LINKED ISSUE #3: Enhance model accuracy through test train split adjustment
Adjust the test train split in efforts to enhance overall model accuracy. Update the `.pkl` model file.

### PR DESCRIPTION
**Pull request by vaibhavsijaria**
Changed train test split to 0.09 from 0.99 to increase accuracy to 91.07%
1st commit contains updated loanmodel.pkl and 2nd commit has updated jupyter notebook
Fixed issue #3

### CODE REVIEW

**Comment by rsashank** [comment]
Good work @vaibhavsijaria 
PR title should be of the format `fixes #<issue number>` (example `fixes #3`). Also make use of conventional commit messages. 

Resources:
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by vaibhavsijaria** [comment]
Hi @rsashank , I have edited pr name and commit message according to the instructions. Please review it. Thank you

**Comment by rsashank** [comment]
@vaibhavsijaria It appears that the accuracy in the  `loan_approval.ipynb` file still seems to be `67.60%` . Have you executed the code cells again?

**Comment by vaibhavsijaria** [comment]
@rsashank sorry for confusion. I have created a single clean commit and pr with both notebook and model pkl file update. Please check #24

**Pull request closed without merging**
